### ISSUE TITLE
Order count wrong--displays duplicate listings

### ISSUE THREAD

**Issue by cmm2t** [uvalib-dcs/tracksys#110]
Have a look at this search--it lists 52 orders (I think), when in fact there are only 4 orders.  Also, at the bottom of the page, it says it is displaying all 6 orders.  Very confusing . . .  

https://tracksys.lib.virginia.edu/admin/orders?q[bibls_id_eq]=8739

**Comment by sdm7g** [comment]
Re-discovered this issue on Daily Progress. There is only one order, but it gets repeated for each unit: 
  SQL (12.1ms)  SELECT `bibls`.id FROM `bibls` INNER JOIN `units` ON `bibls`.`id` = `units`.`bibl_id` WHERE `units`.`order_id` = 5341

Lists the same order 8770 times (once for each unit)
Need to add something to select the uniq order_ids.

**Comment by sdm7g** [comment]
Added :uniq scope to hydraulics Bibl & Order.
Added reference to :uniq scope to ActiveAdmin pages.
Changed Bibl.orders and Order.bibls links from those pages to use :uniq scope. 
CLOSED. 
( There may be a similar issue with other models, but this is the only ones reported or seen by me. )
b86585d7920a7049b86f903ac0208e290b484286
123689d09401a7a56b6f15dfcd3611b5f7d13fb4
74aaa21f4e3aaf7980a8af38920f978d7e4b0bf6 ( in hydraulics library:  https://github.com/uvalib-dcs/hydraulics/commit/9bf9490097ef52c7752a1be3c290c98b1345c8c2 )
